# Generated by Django 6.0.3 on 2026-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='plan_suscripcion',
            field=models.CharField(choices=[('Basico', 'Básico'), ('Profesional', 'Profesional'), ('Premium', 'Premium')], default='Basico', max_length=50),
        ),
    ]
