"""
Migración para alterar el campo CI (Carnet de Identidad) del modelo Paciente.
"""
# pylint: disable=invalid-name
# Generated by Django 6.0.3 on 2026-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Clase de migración que aplica modificaciones al campo 'ci' de Paciente.
    """

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="ci",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
