# Generated by Django 6.0.3 on 2026-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
