# Generated by Django 6.0.3 on 2026-04-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(help_text='Clínica obligatoria para la segregación de datos (RF-29)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
    ]
