# Generated by Django 6.0.3 on 2026-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_es_psicologo_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historia_clinica_nro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
