# Generated by Django 6.0.3 on 2026-04-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
