# Generated by Django 6.0.3 on 2026-04-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clinica_email_contacto_clinica_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BASIC', 'Plan Básico'), ('PRO', 'Plan Profesional'), ('PREMIUM', 'Plan Premium')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('max_pacientes', models.IntegerField(default=50, help_text='Límite máximo de pacientes por clínica en este plan.')),
                ('max_psicologos', models.IntegerField(default=3, help_text='Límite máximo de psicólogos por clínica en este plan.')),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en USD por mes.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada'), ('TRIAL', 'Período de Prueba')], default='TRIAL', max_length=15)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de expiración de la suscripción.', null=True)),
                ('clinica', models.OneToOneField(help_text='[RF-29] Cada clínica tiene exactamente una suscripción.', on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='core.clinica')),
                ('plan', models.ForeignKey(help_text='Plan al que está suscrita la clínica.', on_delete=django.db.models.deletion.PROTECT, to='core.plansuscripcion')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
