# Generated by Django 6.0.3 on 2026-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_paciente_historia_clinica_nro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
