# Generated by Django 6.0.3 on 2026-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_suscripcion_saas_t025'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad clínica (ej. Psicología Infantil)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_atencion',
            field=models.TextField(blank=True, help_text='Horario de atención en formato texto libre', null=True),
        ),
    ]
