# Generated by Django 6.0.3 on 2026-04-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_especialidad_usuario_horario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo Institucional (Tenant)', max_length=500, null=True),
        ),
    ]
