# Generated by Django 6.0.3 on 2026-04-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clinica_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clinica'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(blank=True, help_text='Clínica obligatoria para la segregación de datos (RF-29). Opcional para pacientes huérfanos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clinica'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PSICOLOGO', 'Psicólogo'), ('PACIENTE', 'Paciente'), ('RECEPCIONISTA', 'Recepcionista')], default='PSICOLOGO', max_length=20),
        ),
    ]
