# Generated by Django 6.0.3 on 2026-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paciente_clinica_alter_usuario_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
