# Generated by Django 6.0.3 on 2026-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paciente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='origen',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOVIL', 'Móvil')], default='WEB', max_length=10),
        ),
    ]
