# Generated by Django 6.0.3 on 2026-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paciente_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
