# Generated by Django 6.0.3 on 2026-05-06 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0002_add_especialidad_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='forzar_cambio_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_fecha_pass',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
