# Generated by Django 6.0.3 on 2026-05-06 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0002_add_especialidad_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_cambio_password',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
