# Generated by Django 6.0.3 on 2026-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0003_usuario_forzar_cambio_pass_usuario_ultima_fecha_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='horario_atencion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
