# Generated by Django 6.0.3 on 2026-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0004_dispositivomovil'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='suscripcion_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='suscripcion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
