# Generated by Django 6.0.3 on 2026-05-27 04:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0004_usuario_horario_atencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='forzar_cambio_pass',
            new_name='debe_cambiar_password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='horario_atencion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_fecha_pass',
        ),
        migrations.AddField(
            model_name='clinica',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='clinica',
            name='especialidades',
            field=models.TextField(blank=True, default='', help_text='Lista de especialidades de la clínica, separadas por comas'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='horarios_atencion',
            field=models.CharField(blank=True, default='Lunes a Viernes 08:00 - 18:00', max_length=255),
        ),
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cancelaciones_hoy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_cancelacion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_cambio_password',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DispositivoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARGA', 'Carga de Saldo'), ('PAGO_SUSCRIPCION', 'Pago de Suscripción'), ('INGRESO_PACIENTE', 'Ingreso por Pago de Paciente'), ('OTRO', 'Otro')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(default='TRANSFERENCIA', max_length=50)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_facturacion', to='P1_Identidad_Acceso.clinica')),
            ],
        ),
    ]
