# Generated by Django 6.0.3 on 2026-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0004_usuario_horario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_notif_citas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_notif_reportes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='push_notif_alertas',
            field=models.BooleanField(default=True),
        ),
    ]
