# Generated by Django 6.0.3 on 2026-05-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0005_clinica_suscripcion_activa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='suscripcion_activa',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='suscripcion_expira',
        ),
    ]
