# Generated by Django 6.0.3 on 2026-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0006_remove_clinica_suscripcion_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
