# Generated by Django 6.0.3 on 2026-05-10 20:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0007_clinica_email_contacto_clinica_logo_clinica_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 10, 20, 10, 25, 410401, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TransaccionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARGA', 'Carga de Saldo'), ('PAGO_SUSCRIPCION', 'Pago de Suscripción'), ('OTRO', 'Otro')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(default='TRANSFERENCIA', max_length=50)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_facturacion', to='P1_Identidad_Acceso.clinica')),
            ],
        ),
    ]
