# Generated by Django 6.0.3 on 2026-05-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0008_clinica_fecha_creacion_clinica_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccionclinica',
            name='tipo',
            field=models.CharField(choices=[('CARGA', 'Carga de Saldo'), ('PAGO_SUSCRIPCION', 'Pago de Suscripción'), ('INGRESO_PACIENTE', 'Ingreso por Pago de Paciente'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
