# Generated by Django 6.0.3 on 2026-05-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0009_usuario_ci_alter_transaccionclinica_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cancelaciones_hoy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_cancelacion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
