# Generated by Django 6.0.3 on 2026-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0010_usuario_cancelaciones_hoy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='especialidades',
            field=models.TextField(blank=True, default='', help_text='Lista de especialidades de la clínica, separadas por comas'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='horarios_atencion',
            field=models.CharField(blank=True, default='Lunes a Viernes 08:00 - 18:00', max_length=255),
        ),
    ]
