# Generated by Django 6.0.3 on 2026-06-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0005_usuario_email_notif_citas_and_more'),
        ('P1_Identidad_Acceso', '0012_notificacionpush'),
    ]

    operations = [
    ]
