# Generated by Django 6.0.3 on 2026-05-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0002_historiaclinica_evolucionclinica'),
        ('P4_IA_Administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('PAGO', 'Pago de Sesión'), ('DEUDA', 'Cargo de Sesión'), ('AJUSTE', 'Ajuste de Saldo')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='P2_Gestion_Clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='finanzas/comprobantes/')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='P4_IA_Administracion.transaccion')),
            ],
        ),
    ]
