# Generated by Django 6.0.3 on 2026-05-06 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0003_usuario_forzar_cambio_pass_usuario_ultima_fecha_pass'),
        ('P2_Gestion_Clinica', '0002_expedienteclinico_archivoadjunto_notaclinica'),
        ('P4_IA_Administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_clinico', models.TextField(help_text='Notas clínicas base para el diagnóstico')),
                ('resultado_ia', models.TextField()),
                ('probabilidad_acierto', models.FloatField(default=0.0)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P2_Gestion_Clinica.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnóstico IA',
                'verbose_name_plural': 'Diagnósticos IA',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR / Pago Móvil')], default='EFECTIVO', max_length=20)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P1_Identidad_Acceso.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P2_Gestion_Clinica.paciente')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(max_length=50, unique=True)),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='P4_IA_Administracion.transaccion')),
            ],
        ),
    ]
