# Generated by Django 6.0.3 on 2026-05-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0008_clinica_fecha_creacion_clinica_saldo_and_more'),
        ('P4_IA_Administracion', '0002_transaccion_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='P1_Identidad_Acceso.clinica'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
