# Generated by Django 6.0.3 on 2026-05-11 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0002_expedienteclinico_archivoadjunto_notaclinica'),
        ('P4_IA_Administracion', '0002_diagnosticoia_transaccion_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoia',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='P2_Gestion_Clinica.paciente'),
        ),
    ]
