# Generated by Django 6.0.3 on 2026-06-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P4_IA_Administracion', '0003_alter_diagnosticoia_paciente'),
        ('P4_IA_Administracion', '0003_logauditoria_clinica_logauditoria_ip_address_and_more'),
    ]

    operations = [
    ]
