# Generated by Django 6.0.3 on 2026-04-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('P1_Identidad_Acceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P1_Identidad_Acceso.clinica')),
            ],
        ),
    ]
