# Generated by Django 6.0.3 on 2026-05-06 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('antecedentes_familiares', models.TextField(blank=True, default='')),
                ('antecedentes_personales', models.TextField(blank=True, default='')),
                ('diagnostico_preliminar', models.TextField(blank=True, default='')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='P2_Gestion_Clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateTimeField(auto_now_add=True)),
                ('notas_sesion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='historias/adjuntos/')),
                ('analisis_ia', models.TextField(blank=True, default='', help_text='Resultado del análisis predictivo de IA')),
                ('psicologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='P2_Gestion_Clinica.historiaclinica')),
            ],
        ),
    ]
