# Generated by Django 6.0.3 on 2026-05-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0002_historiaclinica_evolucionclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
