# Generated by Django 6.0.3 on 2026-05-27 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0004_usuario_horario_atencion'),
        ('P2_Gestion_Clinica', '0002_expedienteclinico_archivoadjunto_notaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='P1_Identidad_Acceso.clinica'),
        ),
    ]
