# Generated by Django 6.0.3 on 2026-06-21 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0002_expedienteclinico_archivoadjunto_notaclinica'),
        ('P3_Logistica_Citas', '0002_cita_duracion_minutos_alter_cita_estado_listaespera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_inicial', models.TextField(help_text='Diagnóstico al inicio del tratamiento')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del tratamiento')),
                ('diagnostico_final', models.TextField(blank=True, default='', help_text='Diagnóstico al cierre del tratamiento')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de cierre del tratamiento', null=True)),
                ('estado', models.CharField(choices=[('EN_TRATAMIENTO', 'En tratamiento'), ('ALTA', 'Alta'), ('ABANDONO', 'Abandono')], default='EN_TRATAMIENTO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico_global', to='P2_Gestion_Clinica.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnóstico del Paciente',
                'verbose_name_plural': 'Diagnósticos de Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField(help_text='Fecha de la sesión clínica')),
                ('diagnostico', models.TextField(help_text='Diagnóstico de esta sesión')),
                ('observaciones', models.TextField(blank=True, default='', help_text='Observaciones generales de la sesión')),
                ('estado_animo', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('CRITICO', 'Crítico')], default='REGULAR', max_length=10)),
                ('recomendacion', models.TextField(blank=True, default='', help_text='Recomendación del psicólogo al paciente para esta sesión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='P3_Logistica_Citas.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='P2_Gestion_Clinica.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evolución Clínica',
                'verbose_name_plural': 'Evoluciones Clínicas',
                'ordering': ['-fecha_sesion'],
            },
        ),
    ]
