# Generated by Django 6.0.3 on 2026-05-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0003_paciente_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='strikes_diarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ultimo_strike_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
