# Generated by Django 6.0.3 on 2026-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0012_notificacionpush'),
        ('P2_Gestion_Clinica', '0004_paciente_strikes_diarios_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('clinica', 'ci')},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='strikes_diarios',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ultimo_strike_fecha',
        ),
    ]
