# Generated by Django 6.0.3 on 2026-06-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0003_diagnosticopaciente_evolucion'),
        ('P2_Gestion_Clinica', '0005_alter_paciente_unique_together_alter_paciente_ci_and_more'),
    ]

    operations = [
    ]
