# Generated by Django 6.0.3 on 2026-05-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2_Gestion_Clinica', '0002_historiaclinica_evolucionclinica'),
        ('P3_Logistica_Citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('observacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperas', to='P2_Gestion_Clinica.paciente')),
            ],
            options={
                'ordering': ['prioridad', 'fecha_registro'],
            },
        ),
    ]
