# Generated by Django 6.0.3 on 2026-05-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0003_usuario_forzar_cambio_pass_usuario_ultima_fecha_pass'),
        ('P2_Gestion_Clinica', '0002_expedienteclinico_archivoadjunto_notaclinica'),
        ('P3_Logistica_Citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración estimada de la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P1_Identidad_Acceso.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P2_Gestion_Clinica.paciente')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['-prioridad', 'fecha_registro'],
            },
        ),
    ]
