# Generated by Django 6.0.3 on 2026-05-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P1_Identidad_Acceso', '0005_rename_forzar_cambio_pass_usuario_debe_cambiar_password_and_more'),
        ('P3_Logistica_Citas', '0002_cita_duracion_minutos_alter_cita_estado_listaespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='P1_Identidad_Acceso.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='codigo_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cita',
            name='numero_ficha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
