# Generated by Django 6.0.3 on 2026-05-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P3_Logistica_Citas', '0003_cita_clinica_cita_codigo_qr_cita_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADA', 'Programada'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PENDIENTE', max_length=20),
        ),
    ]
