# Generated by Django 6.0.3 on 2026-05-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P3_Logistica_Citas', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
    ]
