# Generated by Django 6.0.3 on 2026-05-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P3_Logistica_Citas', '0004_cita_estado_pago_cita_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pago Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20),
        ),
    ]
