# Generated by Django 6.0.3 on 2026-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P3_Logistica_Citas', '0005_alter_cita_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='codigo_qr',
            field=models.TextField(blank=True, help_text='Datos para generar QR en frontend', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='numero_ficha',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
