# Generated by Django 6.0.3 on 2026-06-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P3_Logistica_Citas', '0002_cita_duracion_minutos_alter_cita_estado_listaespera'),
        ('P3_Logistica_Citas', '0006_cita_codigo_qr_cita_numero_ficha'),
    ]

    operations = [
    ]
